/**
 * InsightList — renders a list of deterministic insights generated by
 * `src/lib/insights.ts`. Renders nothing if the list is empty.
 *
 * Icons are minimal SVG (no emoji) for an editorial, premium feel.
 */

import { Insight, InsightIconKind, InsightVariant } from '@/lib/insights';
import { Icons } from '@/components/icons';

interface InsightListProps {
  insights: Insight[];
  /** Section heading. Defaults to "Insights". Pass `null` to omit. */
  heading?: string | null;
}

/** Default icon per variant when an Insight doesn't override. */
const DEFAULT_ICON: Record<InsightVariant, InsightIconKind> = {
  positive: 'check',
  neutral:  'info',
  caution:  'alert',
};

function InsightIcon({ kind }: { kind: InsightIconKind }) {
  switch (kind) {
    case 'trophy': return <Icons.Trophy size={18}/>;
    case 'check':  return <Icons.CheckCircle size={18}/>;
    case 'info':   return <Icons.Info size={18}/>;
    case 'alert':  return <Icons.Alert size={18}/>;
  }
}

export function InsightList({ insights, heading = 'Insights' }: InsightListProps) {
  if (insights.length === 0) return null;

  return (
    <div className="insights">
      {heading && <div className="insights-head">{heading}</div>}
      {insights.map(ins => {
        const iconKind = ins.icon ?? DEFAULT_ICON[ins.variant];
        return (
          <div key={ins.id} className={`insight-item ${ins.variant}`}>
            <span className="insight-icon"><InsightIcon kind={iconKind}/></span>
            <span className="insight-text">{ins.text}</span>
          </div>
        );
      })}
    </div>
  );
}
