/**
 * InsightList — renders a list of deterministic insights generated by
 * `src/lib/insights.ts`. Renders nothing if the list is empty.
 */

import { Insight } from '@/lib/insights';

interface InsightListProps {
  insights: Insight[];
  /** Section heading. Defaults to "INSIGHTS". Pass `null` to omit. */
  heading?: string | null;
}

const DEFAULT_EMOJI: Record<string, string> = {
  positive: '✓',
  caution:  '!',
  neutral:  '·',
};

export function InsightList({ insights, heading = 'Insights' }: InsightListProps) {
  if (insights.length === 0) return null;

  return (
    <div className="insights">
      {heading && <div className="insights-head">{heading}</div>}
      {insights.map(ins => (
        <div key={ins.id} className={`insight-item ${ins.variant}`}>
          <span className="insight-emoji">{ins.emoji ?? DEFAULT_EMOJI[ins.variant]}</span>
          <span className="insight-text">{ins.text}</span>
        </div>
      ))}
    </div>
  );
}
